// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'id'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	message: {
		/**
		 * F​R​E​E​ ​S​U​P​E​R​ ​F​A​S​T​ ​W​I​F​I
		 */
		welcome: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​p​h​o​n​e​ ​n​u​m​b​e​r​ ​b​e​l​o​w​ ​t​o​ ​g​e​t​ ​y​o​u​r​ ​w​i​f​i​ ​p​a​s​s​w​o​r​d​.
		 */
		caption: string
	}
	input: {
		/**
		 * T​y​p​e​ ​p​h​o​n​e​ ​n​u​m​b​e​r​ ​h​e​r​e
		 */
		placeHolderPhoneNumber: string
		/**
		 * P​l​e​a​s​e​ ​t​u​r​n​ ​o​n​ ​t​h​e​ ​n​o​t​i​f​i​c​a​t​i​o​n​ ​f​i​r​s​t
		 */
		placeHolderPhoneNumberOffNotif: string
	}
	button: {
		/**
		 * L​o​g​i​n
		 */
		login: string
	}
	notSupport: {
		/**
		 * B​r​o​w​s​e​r​ ​N​o​t​ ​S​u​p​p​o​r​t​e​d​!
		 */
		title: string
		/**
		 * P​l​e​a​s​e​ ​U​s​e​ ​C​h​r​o​m​e​ ​t​o​ ​c​o​n​t​i​n​u​e​.
		 */
		caption: string
		button: {
			/**
			 * O​p​e​n​ ​W​i​t​h​ ​C​h​r​o​m​e
			 */
			title: string
			/**
			 * C​o​p​y​ ​t​o​ ​c​l​i​p​b​o​a​r​d
			 */
			caption: string
		}
	}
}

export type TranslationFunctions = {
	message: {
		/**
		 * FREE SUPER FAST WIFI
		 */
		welcome: () => LocalizedString
		/**
		 * Enter your phone number below to get your wifi password.
		 */
		caption: () => LocalizedString
	}
	input: {
		/**
		 * Type phone number here
		 */
		placeHolderPhoneNumber: () => LocalizedString
		/**
		 * Please turn on the notification first
		 */
		placeHolderPhoneNumberOffNotif: () => LocalizedString
	}
	button: {
		/**
		 * Login
		 */
		login: () => LocalizedString
	}
	notSupport: {
		/**
		 * Browser Not Supported!
		 */
		title: () => LocalizedString
		/**
		 * Please Use Chrome to continue.
		 */
		caption: () => LocalizedString
		button: {
			/**
			 * Open With Chrome
			 */
			title: () => LocalizedString
			/**
			 * Copy to clipboard
			 */
			caption: () => LocalizedString
		}
	}
}

export type Formatters = {}
